language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.jsenv:
  secure: "G4LdiLq+Ng0tvNIyENgLLByEd462CbFx/kVW9SV0NMD8/p3QbG3n3dUCvyIsSOcRcowHZIMwJ/nqZmcb6Po5eqIjLQaXTIuTh5sWVZVQer74dgTuaonzsln5Gqw1EK063lmzkmRpmrYtuLjxlnIRqzXyAWmqa4zKSF33WOANPK8pc2xI8n4niHdTdoUc4fLLs4nsaTQkF/n7w7gLyLlkG3zl1Y79gm0hMliC58exFDmgMZmNAdLT47zAt6AqY6ixGj3IAwj3YxhubfVlK5o+ayi2u1U9YsVmkIO2yvujtzydM9b3DJiodFrmJDAAQket8STz1q+pKKt5jQJZk+LRzk57tyZzNcQTJXtmyyyMgdlysrO8QvXh82fZE814nxwasweXrJVrJ2KJ9iZByIjosREqKrjwybozXaYs9eh+Zlfq/r2qNLaHQTTm0qBF4UQ60fJJp/IzzV7coPfmPtoJcX9/7nEG4yG0qrY2fZnItRS4IJC8n3y0+/obOfSCXVAGJYLvJZToRSo2gf59MJuBQnJjywne1eZNJZZmWJysbFx+r37kALSmPO0XZeGqdWVBslUG5bf/ZRngK6Bt/kJnEzmu0mNqUH7C+52IedHmuZuJpWIgeLmTjlkyKHFvWeLr+nPC7S+Ky1w221e95WqD1bAUL455pCMhjduYNrjSaGI="